"""create_agent_notes_schema

Revision ID: 431daf3f2217
Revises: 65e35ac5b3d6
Create Date: 2026-08-29 10:47:37.280529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '431daf3f2217'
down_revision: Union[str, None] = '65e35ac5b3d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_notes_agent_id'), 'agent_notes', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_notes_conversation_id'), 'agent_notes', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_notes_conversation_id'), table_name='agent_notes')
    op.drop_index(op.f('ix_agent_notes_agent_id'), table_name='agent_notes')
    op.drop_table('agent_notes')
    # ### end Alembic commands ###
